sudo: required
language: python
python: 3.6
services:
- docker
env:
  global:
    secure: IST0QlHj3cnfN+TCdGgWR1Nio7pbZUP2vyy639qbkZiCe1Lfq6S9YONTXia0LY5SCnqb3PloBfgomWNJw3fIKast5d2YuuRMiZShUji0W8OUSFQnUeFtr9RcCQ7/e1gLODhc5z7tegHk60G25Vi3p282SP9fYY+5q6XwV/VZh6nmyvsrLcQspwCM/OHOKSL8DCHFLSFZKGFGLOr6vVyFElPQzj3IUC7uaofzmiKx5yXJtnEaQgqX5aSNBlUfajUlU/SfzcwX8Q2ypmISe1GEAaDiwqRK0K61Euq/xCV1pzv1CjYs4WIjBHsN6eSK5IErAHK3PKCIoLpcXav6nwFqith1a3hmAmxwwqTzXvkNz2HcvFtI9xDRfy2o6JIwfqverA6sk4p0G09NuCEmJn2yhG+JPRAzYLYwvu91LxvB+621n7YkrtGWkLDRFhvD6TlGnOcCWAPiwigf9b48MZIpnpiy+MebEpDIZ0nik8oosVbYEYewSJuQYb5gt4Fk46n9HR+EfPrRw1SJ7JceBnZhN4jGBxIbuRXMZI6mICQ1bXT04swrrPAl+udy7KaRuZ2GtTNbDQluXQByrofnVEdqBdUUwevDR8UO9XY5OA2STH/GL1HpIcgSlvBsbBbirFhYFA9dWAHtSLzQh9PwdjpG6OoCukFViYJv/4VsU2d7Tq4=
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate galaxy_training_material
- make install
before_script:
- pip install vl pyyaml
- vl --version
script:
- set -e
- make site
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]
  then
    bin/publish
  fi
