name: galaxy_training_material
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- asn1crypto=0.24.0
- ca-certificates=2018.4.16
- certifi=2018.4.16
- cffi=1.11.5
- chardet=3.0.4
- cryptography=2.2.1
- gettext=0.19.8.1
- gmp=6.1.2
- idna=2.6
- jemalloc=5.0.1
- libffi=3.2.1
- libiconv=1.15
- mkl_fft=1.0.2
- mkl_random=1.0.1
- ncurses=5.9
- nodejs=9.11.1
- openssl=1.0.2o
- pandas=0.22.0
- pip=9.0.3
- pycparser=2.18
- pyopenssl=17.5.0
- pysocks=1.6.8
- python=3.6.5
- python-dateutil=2.7.2
- pytz=2018.4
- pyyaml=3.12
- readline=7.0
- requests=2.18.4
- ruby=2.4.4
- setuptools=39.1.0
- six=1.11.0
- sqlite=3.20.1
- tk=8.6.7
- urllib3=1.22
- wheel=0.31.0
- xz=5.2.3
- yaml=0.1.7
- yamllint=1.11.0
- zlib=1.2.11
- intel-openmp=2018.0.0
- libgfortran=3.0.1
- mkl=2018.0.2
- numpy=1.14.2
- pip:
  - mkl-fft==1.0.2
  - mkl-random==1.0.1
  - pathspec==0.5.6

