name: galaxy_training_material
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- ruby=2.2.3=1
- jemalloc=4.4.0=0
- gmp=6.1.0=0
- openssl=1.0.2l=0
- readline=6.2=2
- yaml=0.1.6=0
- zlib=1.2.8=3
