---
name: galaxy_training_material
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - ruby
  - jemalloc
  - gmp
  - openssl
  - readline
  - yaml
  - zlib
  - yamllint
  - nodejs
  - libiconv
